sequenceDiagram
    participant Wallet
    participant Scanner as SP Scanner
    participant BFM as Block Filter Manager
    participant BP as Block Processor
    participant BC as Bitcoin Core Node

    Wallet->>Scanner: Register scan keys
    Scanner-->>+BP: subscribe new blocks
    
    %% Block Processor syncs with Bitcoin Core Node asynchronously
    BC-->>BP: New Block
    Note right of BP: compute tweak 
    Note right of BP: index unspent outputs
    BP-->>BP: compute tweak
    BP-->>-Scanner: new block

    %% Block Filter Manager
    BP-->>+BFM: new block
    BFM-->>BFM: compute spent

    %% Wallet requests from Block Processor (does not trigger block fetch)
    Scanner->>+BP: Request tweaks & UTXOs for block(s)
    BP-->>-Scanner: Tweaks & relevant UTXOs

    Scanner->>+BFM: Request filters
    BFM-->>BFM: build taproot GCS filter
    BFM-->>-Scanner: utxo and outpoint filters
    Scanner-->>Scanner: calculate UTXOs
    
    Note over Wallet,Scanner: async update
    Wallet-->>+Scanner: subscribe to UTXOs
    Scanner-->>-Wallet: new owned UTXOs